#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

cd "$(dirname "$0")/.."   # run from the project root, wherever the wizard is called from
STUDY_DIR="study"
mkdir -p "$STUDY_DIR"

banner "TrialSeal: the steps only a person can do"

# ── Model keys: the forecasters that are frontier models as shipped ────────
stage "Anthropic API key"
say "Used to query Claude models as forecasters. Stored in .env, which git ignores."
open_url "https://console.anthropic.com/settings/keys"
step "Create a key named 'trialseal' and copy it. If the page has moved, look for API keys in the console."
ask_secret ANTHROPIC_API_KEY "Paste the key (Enter to skip):"
if [[ -n "$ANTHROPIC_API_KEY" ]]; then write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"; else SKIPPED+=("Anthropic API key"); fi

stage "OpenAI API key"
say "Used to query OpenAI models as forecasters."
open_url "https://platform.openai.com/api-keys"
step "Create a secret key named 'trialseal' and copy it."
ask_secret OPENAI_API_KEY "Paste the key (Enter to skip):"
if [[ -n "$OPENAI_API_KEY" ]]; then write_env OPENAI_API_KEY "$OPENAI_API_KEY"; else SKIPPED+=("OpenAI API key"); fi

stage "Google API key"
say "Used to query Gemini models as forecasters."
open_url "https://aistudio.google.com/apikey"
step "Create an API key and copy it."
ask_secret GOOGLE_API_KEY "Paste the key (Enter to skip):"
if [[ -n "$GOOGLE_API_KEY" ]]; then write_env GOOGLE_API_KEY "$GOOGLE_API_KEY"; else SKIPPED+=("Google API key"); fi

# ── Time-stamping: two independent services that anchor each seal ──────────
stage "Time-stamping services"
say "Each seal is anchored by two independent services, one of each kind."
say "Both defaults were checked against the real services on 2026-10-08."
# Keep what was recorded on an earlier run unless a new address is typed.
recorded() { python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get(sys.argv[2], ""))' "$STUDY_DIR/anchors.json" "$1" 2>/dev/null || true; }
RFC3161_DEFAULT=$(recorded rfc3161); RFC3161_DEFAULT="${RFC3161_DEFAULT:-http://timestamp.digicert.com}"
OTS_DEFAULT=$(recorded opentimestamps); OTS_DEFAULT="${OTS_DEFAULT:-https://alice.btc.calendar.opentimestamps.org}"
note "RFC 3161 authority. DigiCert's replies verify against the standard certificate bundle."
printf '  %sRFC 3161 URL%s %s[Enter for %s]%s ' "$BOLD" "$RESET" "$DIM" "$RFC3161_DEFAULT" "$RESET"
read -r RFC3161_URL || true
note "OpenTimestamps calendar. Alternative: https://bob.btc.calendar.opentimestamps.org"
printf '  %sCalendar URL%s %s[Enter for %s]%s ' "$BOLD" "$RESET" "$DIM" "$OTS_DEFAULT" "$RESET"
read -r OTS_CALENDAR || true
RFC3161_URL="${RFC3161_URL:-$RFC3161_DEFAULT}" OTS_CALENDAR="${OTS_CALENDAR:-$OTS_DEFAULT}" python3 -c '
import json, os, sys
json.dump({"rfc3161": os.environ["RFC3161_URL"], "opentimestamps": os.environ["OTS_CALENDAR"]},
          open(sys.argv[1], "w"), indent=2)
open(sys.argv[1], "a").write("\n")' "$STUDY_DIR/anchors.json"
printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$STUDY_DIR/anchors.json"

# ── Public repository: where seals are pushed ──────────────────────────────
stage "Public repository"
say "Seals (trial lists and commitments, never forecasts) are pushed to a public repository."
CURRENT_ORIGIN=$(git remote get-url origin 2>/dev/null || true)
if [[ -n "$CURRENT_ORIGIN" ]]; then
  say "This project already pushes to: $CURRENT_ORIGIN"
  if ! confirm "Replace it with a different repository?"; then
    REPOSITORY_URL="$CURRENT_ORIGIN"
  fi
fi
if [[ -z "${REPOSITORY_URL:-}" ]]; then
  open_url "https://github.com/organizations/span-ai-labs/repositories/new"
  step "Name it 'trialseal'. Choose Public. Do NOT add a README, licence or .gitignore."
  step "Create it, then copy its HTTPS URL (https://github.com/span-ai-labs/trialseal.git)."
  printf '  %sPaste the repository URL (Enter to skip):%s ' "$BOLD" "$RESET"
  read -r REPOSITORY_URL || true
  if [[ -n "$REPOSITORY_URL" ]]; then
    if [[ -n "$CURRENT_ORIGIN" ]]; then git remote set-url origin "$REPOSITORY_URL"; else git remote add origin "$REPOSITORY_URL"; fi
    printf '  %s✓ set%s origin → %s\n' "$GREEN" "$RESET" "$REPOSITORY_URL"
  fi
fi
if [[ -n "${REPOSITORY_URL:-}" ]]; then
  printf '%s\n' "$REPOSITORY_URL" > "$STUDY_DIR/public_repository.txt"
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$STUDY_DIR/public_repository.txt"
  if git ls-remote --exit-code --heads origin main >/dev/null 2>&1; then
    note "main has already been pushed there; nothing more to do in this stage."
  else
    warn "The first push publishes the whole history: code, glossary, decision records,"
    warn "the spec, the tickets and the research notes. Read them as a stranger would first."
    if confirm "Push everything on main to the public repository now?"; then
      git push -u origin main
      printf '  %s✓ pushed%s main\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("first push to the public repository (git push -u origin main)")
    fi
  fi
else
  SKIPPED+=("public repository (create it, then re-run this wizard)")
fi

# ── Protocol registration: sealing refuses to run without this record ──────
stage "Protocol registration record"
say "Sealing refuses to run until the registered protocol is recorded here."
if [[ -f "$STUDY_DIR/registration.json" ]]; then
  note "A registration is already recorded in $STUDY_DIR/registration.json; delete that file to record it again."
elif confirm "Has the protocol been registered (for example on OSF)?"; then
  printf '  %sRegistry%s %s[Enter for OSF]%s ' "$BOLD" "$RESET" "$DIM" "$RESET"
  read -r REGISTRY || true
  printf '  %sRegistration URL:%s ' "$BOLD" "$RESET"
  read -r REGISTRATION_URL || true
  printf '  %sDate registered (YYYY-MM-DD):%s ' "$BOLD" "$RESET"
  read -r REGISTERED_ON || true
  printf '  %sPath to the protocol file exactly as registered:%s ' "$BOLD" "$RESET"
  read -r PROTOCOL_FILE || true
  # Python checks the date is a real one and writes valid JSON whatever characters were typed.
  if REGISTRY="${REGISTRY:-OSF}" REGISTRATION_URL="$REGISTRATION_URL" REGISTERED_ON="$REGISTERED_ON" python3 -c '
import datetime, hashlib, json, os, sys
url, protocol = os.environ["REGISTRATION_URL"].strip(), sys.argv[2]
datetime.date.fromisoformat(os.environ["REGISTERED_ON"])
assert url and os.path.isfile(protocol)
record = {"registry": os.environ["REGISTRY"], "url": url, "registered_on": os.environ["REGISTERED_ON"],
          "protocol_sha256": hashlib.sha256(open(protocol, "rb").read()).hexdigest()}
json.dump(record, open(sys.argv[1], "w"), indent=2)
open(sys.argv[1], "a").write("\n")' "$STUDY_DIR/registration.json" "$PROTOCOL_FILE" 2>/dev/null; then
    printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$STUDY_DIR/registration.json"
    note "Commit study/registration.json so the record travels with the repository."
  else
    rm -f "$STUDY_DIR/registration.json"
    warn "Need an existing protocol file, a URL and a real date such as 2026-11-01. Nothing was written."
    SKIPPED+=("protocol registration record (re-run this wizard)")
  fi
else
  SKIPPED+=("protocol registration record (run this wizard again after registering)")
fi

finish
